---

language: php

php:
  - 5.5
  
env:
  - DB=mysql
  
before_script:
  - phpenv config-add site.ini
  - echo 'extension = mcrypt.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  
script:
  - phpunit -v app/
