---

language: php

php:
  - 5.5
  
env:
  - DB=mysql
  
services:
  - mysql
  
before_script:
  - phpenv config-add site.ini
  - cd app
  - composer self-update
  - composer install
  - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS replique DEFAULT CHARACTER SET utf8;"
  - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS replique_test DEFAULT CHARACTER SET utf8;"
  - mv config/app.travis.php config/app.php
  
script:
  - vendor/bin/phpunit
