---

language: php

php:
  - 5.5
  
env:
  - DB=mysql
  
services:
  - mysql
  
before_script:
  - phpenv config-add site.ini
  - cd app
  - composer self-update
  - composer install
  - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS replique DEFAULT CHARACTER SET utf8;"
  - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS replique_test DEFAULT CHARACTER SET utf8;"
  - sed -e '$ d' config/app.php >> config/app.temp.php
  - cat ../travis.config.php > config/app.temp.php
  - mv config/app.temp.php config/app.php
  
script:
  - cat config/app.php
#  - vendor/bin/phpunit
