# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "site-provision" do |prov|
     # Every Vagrant virtual environment requires a box to build off of.
     prov.vm.box = "mjp182/CentOS_7"
     prov.vm.provision "shell", path: "provision.sh"

     prov.vm.provider "virtualbox" do |v|
       v.name = 'replique-site-base'
     end
   end
 
end
