# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.ssh.insert_key = false

  config.vm.define "site-provision" do |prov|
     # Every Vagrant virtual environment requires a box to build off of.
     prov.vm.box = "mjp182/CentOS_7"
     prov.vm.provision "shell", path: "provision.sh"

     prov.vm.provider "virtualbox" do |v|
       v.name = 'replique-site-base'
     end
   end

  config.vm.define "site", primary: true do |site|
     site.vm.box = "replique/site"
     site.vm.box_url = "file://./site.box"
	 site.vm.provision "shell", path: "site.sh"
	 
     site.vm.synced_folder "../", "/home/replique/opt/work", owner: "vagrant", group: "vagrant", mount_options: ["dmode=777,fmode=777"]
     
     site.vm.network "forwarded_port", guest: 8765, host: 8765
  end 
end
